export const bus = [
  {
    source: "New York",
    destination: "Boston",
    stops: ["Philadelphia", "Hartford"],
    busName: "Express Bus 101",
    startTime: "08:00 AM",
    endTime: "01:00 PM",
    fare: 50,
    noOfSeatsAvailable: 25,
    layout: {
      rows: 12,
      seatsPerRow: 4,
      seatConfiguration: [
        ["1A", "1B", "1C", "1D"],
        ["2A", "2B", "2C", "2D"],
        ["3A", "3B", "3C", "3D"],
        ["4A", "4B", "4C", "4D"],
        ["5A", "5B", "5C", "5D"],
        ["6A", "6B", "6C", "6D"],
        ["7A", "7B", "7C", "7D"],
        ["8A", "8B", "8C", "8D"],
        ["9A", "9B", "9C", "9D"],
        ["10A", "10B", "10C", "10D"],
        ["11A", "11B", "11C", "11D"],
        ["12A", "12B", "12C", "12D"],
      ],
    },
  },
  {
    source: "New York",
    destination: "Boston",
    stops: ["Philadelphia", "Hartford"],
    busName: "Express Bus 102",
    startTime: "08:00 AM",
    endTime: "01:00 PM",
    fare: 55,
    noOfSeatsAvailable: 25,
    layout: {
      rows: 12,
      seatsPerRow: 4,
      seatConfiguration: [
        ["1A", "1B", "1C", "1D"],
        ["2A", "2B", "2C", "2D"],
        ["3A", "3B", "3C", "3D"],
        ["4A", "4B", "4C", "4D"],
        ["5A", "5B", "5C", "5D"],
        ["6A", "6B", "6C", "6D"],
        ["7A", "7B", "7C", "7D"],
        ["8A", "8B", "8C", "8D"],
        ["9A", "9B", "9C", "9D"],
        ["10A", "10B", "10C", "10D"],
        ["11A", "11B", "11C", "11D"],
        ["12A", "12B", "12C", "12D"],
      ],
    },
  },{
    source: "New York",
    destination: "Boston",
    stops: ["Philadelphia", "Hartford"],
    busName: "Express Bus 103",
    startTime: "08:00 AM",
    endTime: "01:00 PM",
    fare: 70,
    noOfSeatsAvailable: 25,
    layout: {
      rows: 12,
      seatsPerRow: 4,
      seatConfiguration: [
        ["1A", "1B", "1C", "1D"],
        ["2A", "2B", "2C", "2D"],
        ["3A", "3B", "3C", "3D"],
        ["4A", "4B", "4C", "4D"],
        ["5A", "5B", "5C", "5D"],
        ["6A", "6B", "6C", "6D"],
        ["7A", "7B", "7C", "7D"],
        ["8A", "8B", "8C", "8D"],
        ["9A", "9B", "9C", "9D"],
        ["10A", "10B", "10C", "10D"],
        ["11A", "11B", "11C", "11D"],
        ["12A", "12B", "12C", "12D"],
      ],
    },
  },
  {
    source: "San Francisco",
    destination: "Los Angeles",
    stops: ["San Jose", "Santa Barbara"],
    busName: "California Dream Bus",
    startTime: "09:00 AM",
    endTime: "05:00 PM",
    fare: 75,
    noOfSeatsAvailable: 30,
    layout: {
      rows: 10,
      seatsPerRow: 4,
      seatConfiguration: [
        ["1A", "1B", "1C", "1D"],
        ["2A", "2B", "2C", "2D"],
        ["3A", "3B", "3C", "3D"],
        ["4A", "4B", "4C", "4D"],
        ["5A", "5B", "5C", "5D"],
        ["6A", "6B", "6C", "6D"],
        ["7A", "7B", "7C", "7D"],
        ["8A", "8B", "8C", "8D"],
        ["9A", "9B", "9C", "9D"],
        ["10A", "10B", "10C", "10D"],
      ],
    },
  },
  {
    source: "Boston",
    destination: "New York",
    stops: ["Hartford", "Philadelphia"],
    busName: "Cityline Bus 202",
    startTime: "02:00 PM",
    endTime: "07:00 PM",
    fare: 55,
    noOfSeatsAvailable: 20,
    layout: {
      rows: 12,
      seatsPerRow: 4,
      seatConfiguration: [
        ["1A", "1B", "1C", "1D"],
        ["2A", "2B", "2C", "2D"],
        ["3A", "3B", "3C", "3D"],
        ["4A", "4B", "4C", "4D"],
        ["5A", "5B", "5C", "5D"],
        ["6A", "6B", "6C", "6D"],
        ["7A", "7B", "7C", "7D"],
        ["8A", "8B", "8C", "8D"],
        ["9A", "9B", "9C", "9D"],
        ["10A", "10B", "10C", "10D"],
        ["11A", "11B", "11C", "11D"],
        ["12A", "12B", "12C", "12D"],
      ],
    },
  },
  {
    source: "Los Angeles",
    destination: "San Francisco",
    stops: ["Santa Barbara", "San Jose"],
    busName: "Golden Gate Express",
    startTime: "06:00 AM",
    endTime: "01:00 PM",
    fare: 70,
    noOfSeatsAvailable: 18,
    layout: {
      rows: 10,
      seatsPerRow: 4,
      seatConfiguration: [
        ["1A", "1B", "1C", "1D"],
        ["2A", "2B", "2C", "2D"],
        ["3A", "3B", "3C", "3D"],
        ["4A", "4B", "4C", "4D"],
        ["5A", "5B", "5C", "5D"],
        ["6A", "6B", "6C", "6D"],
        ["7A", "7B", "7C", "7D"],
        ["8A", "8B", "8C", "8D"],
        ["9A", "9B", "9C", "9D"],
        ["10A", "10B", "10C", "10D"],
      ],
    },
  },
  {
    source: "Chicago",
    destination: "Detroit",
    stops: ["Kalamazoo", "Ann Arbor"],
    busName: "Great Lakes Bus",
    startTime: "07:00 AM",
    endTime: "12:00 PM",
    fare: 45,
    noOfSeatsAvailable: 22,
    layout: {
      rows: 12,
      seatsPerRow: 4,
      seatConfiguration: [
        ["1A", "1B", "1C", "1D"],
        ["2A", "2B", "2C", "2D"],
        ["3A", "3B", "3C", "3D"],
        ["4A", "4B", "4C", "4D"],
        ["5A", "5B", "5C", "5D"],
        ["6A", "6B", "6C", "6D"],
        ["7A", "7B", "7C", "7D"],
        ["8A", "8B", "8C", "8D"],
        ["9A", "9B", "9C", "9D"],
        ["10A", "10B", "10C", "10D"],
        ["11A", "11B", "11C", "11D"],
        ["12A", "12B", "12C", "12D"],
      ],
    },
  },
];

export const train = [
  {
    trainName: "Coastal Express",
    source: "San Francisco",
    destination: "Los Angeles",
    startTime: "09:00 AM",
    endTime: "01:00 PM",
    stops: ["San Jose", "Santa Barbara"],
    coaches: [
      {
        coachName: "Sleeper",
        noOfSeatsAvailable: 10,
        fare: 120,
      },
      {
        coachName: "AC First Class",
        noOfSeatsAvailable: 5,
        fare: 200,
      },
      {
        coachName: "AC 2-Tier",
        noOfSeatsAvailable: 15,
        fare: 150,
      },
      {
        coachName: "AC 3-Tier",
        noOfSeatsAvailable: 20,
        fare: 100,
      },
    ],
  },{
    trainName: "Coastal Express",
    source: "Los Angeles",
    destination: "San Francisco",
    startTime: "09:00 AM",
    endTime: "01:00 PM",
    stops: ["San Jose", "Santa Barbara"],
    coaches: [
      {
        coachName: "Sleeper",
        noOfSeatsAvailable: 10,
        fare: 130,
      },
      {
        coachName: "AC First Class",
        noOfSeatsAvailable: 5,
        fare: 210,
      },
      {
        coachName: "AC 2-Tier",
        noOfSeatsAvailable: 15,
        fare: 160,
      },
      {
        coachName: "AC 3-Tier",
        noOfSeatsAvailable: 20,
        fare: 110,
      },
    ],
  },
  {
    trainName: "Northeast Regional",
    source: "New York",
    destination: "Boston",
    startTime: "07:00 AM",
    endTime: "10:00 AM",
    stops: ["Philadelphia", "Hartford"],
    coaches: [
      {
        coachName: "Sleeper",
        noOfSeatsAvailable: 5,
        fare: 180,
      },
      {
        coachName: "AC First Class",
        noOfSeatsAvailable: 10,
        fare: 220,
      },
      {
        coachName: "AC 2-Tier",
        noOfSeatsAvailable: 20,
        fare: 130,
      },
      {
        coachName: "AC 3-Tier",
        noOfSeatsAvailable: 25,
        fare: 90,
      },
    ],
  },
  {
    trainName: "Pacific Surfliner",
    source: "San Diego",
    destination: "Los Angeles",
    startTime: "08:00 AM",
    endTime: "10:00 AM",
    stops: ["Oceanside", "Santa Ana"],
    coaches: [
      {
        coachName: "Business Class",
        noOfSeatsAvailable: 15,
        fare: 150,
      },
      {
        coachName: "Economy Class",
        noOfSeatsAvailable: 30,
        fare: 80,
      },
    ],
  },
  {
    trainName: "Empire Builder",
    source: "Chicago",
    destination: "Seattle",
    startTime: "12:00 PM",
    endTime: "08:00 AM",
    stops: ["Minneapolis", "Spokane"],
    coaches: [
      {
        coachName: "Sleeper",
        noOfSeatsAvailable: 10,
        fare: 250,
      },
      {
        coachName: "AC First Class",
        noOfSeatsAvailable: 8,
        fare: 300,
      },
      {
        coachName: "Economy",
        noOfSeatsAvailable: 50,
        fare: 150,
      },
    ],
  },
];

export const flight = [
  {
    source: "London",
    destination: "New York",
    stops: ["Reykjavik"],
    flightName: "Atlantic Airways",
    baseFare: 200,
    startTime: "10:00 AM",
    endTime: "01:00 PM",
    noOfSeatsAvailable: 190,
    layout: {
      rows: 15,
      seatsPerRow: 4,
      seatConfiguration: [
        ["1A", "1B", "1C", "1D"],
        ["2A", "2B", "2C", "2D"],
        ["3A", "3B", "3C", "3D"],
        ["4A", "4B", "4C", "4D"],
        ["5A", "5B", "5C", "5D"],
        ["6A", "6B", "6C", "6D"],
        ["7A", "7B", "7C", "7D"],
        ["8A", "8B", "8C", "8D"],
        ["9A", "9B", "9C", "9D"],
        ["10A", "10B", "10C", "10D"],
        ["11A", "11B", "11C", "11D"],
        ["12A", "12B", "12C", "12D"],
        ["13A", "13B", "13C", "13D"],
        ["14A", "14B", "14C", "14D"],
        ["15A", "15B", "15C", "15D"],
      ],
    },
    seatCategories: [
      { name: "Economy", price: 500, rows: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] }, // Rows 6-15 are Economy Class
      { name: "Business", price: 1500, rows: [1, 2] }, // Rows 1-2 are Business Class
      { name: "First Class", price: 3000, rows: [0] }, // Row 1 is First Class
    ],
  },
  {
    source: "New York",
    destination: "Los Angeles",
    stops: ["Chicago"],
    flightName: "Pacific Airlines",
    baseFare: 350,
    startTime: "03:00 PM",
    endTime: "06:00 PM",
    noOfSeatsAvailable: 260,
    layout: {
      rows: 15,
      seatsPerRow: 4,
      seatConfiguration: [
        ["1A", "1B", "1C", "1D"],
        ["2A", "2B", "2C", "2D"],
        ["3A", "3B", "3C", "3D"],
        ["4A", "4B", "4C", "4D"],
        ["5A", "5B", "5C", "5D"],
        ["6A", "6B", "6C", "6D"],
        ["7A", "7B", "7C", "7D"],
        ["8A", "8B", "8C", "8D"],
        ["9A", "9B", "9C", "9D"],
        ["10A", "10B", "10C", "10D"],
        ["11A", "11B", "11C", "11D"],
        ["12A", "12B", "12C", "12D"],
        ["13A", "13B", "13C", "13D"],
        ["14A", "14B", "14C", "14D"],
        ["15A", "15B", "15C", "15D"],
      ],
    },
    seatCategories: [
      { name: "Economy", price: 350, rows: [3,4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] }, // Rows 6-15 are Economy Class
      { name: "Business", price: 1200, rows: [1, 2] }, // Rows 1-2 are Business Class
      { name: "First Class", price: 2500, rows: [0] }, // Row 1 is First Class
    ],
  },{
    source: "Los Angeles",
    destination: "New York",
    stops: ["Chicago"],
    flightName: "Pacific Airlines",
    baseFare: 350,
    startTime: "03:00 PM",
    endTime: "06:00 PM",
    noOfSeatsAvailable: 260,
    layout: {
      rows: 15,
      seatsPerRow: 4,
      seatConfiguration: [
        ["1A", "1B", "1C", "1D"],
        ["2A", "2B", "2C", "2D"],
        ["3A", "3B", "3C", "3D"],
        ["4A", "4B", "4C", "4D"],
        ["5A", "5B", "5C", "5D"],
        ["6A", "6B", "6C", "6D"],
        ["7A", "7B", "7C", "7D"],
        ["8A", "8B", "8C", "8D"],
        ["9A", "9B", "9C", "9D"],
        ["10A", "10B", "10C", "10D"],
        ["11A", "11B", "11C", "11D"],
        ["12A", "12B", "12C", "12D"],
        ["13A", "13B", "13C", "13D"],
        ["14A", "14B", "14C", "14D"],
        ["15A", "15B", "15C", "15D"],
      ],
    },
    seatCategories: [
      { name: "Economy", price: 350, rows: [3,4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] }, // Rows 6-15 are Economy Class
      { name: "Business", price: 1200, rows: [1, 2] }, // Rows 1-2 are Business Class
      { name: "First Class", price: 2500, rows: [0] }, // Row 1 is First Class
    ],
  },
  {
    source: "Detroit",
    destination: "Chicago",
    stops: ["Ann Arbor", "Kalamazoo"],
    flightName: "Midwest Flyer",
    baseFare: 50,
    startTime: "01:00 PM",
    endTime: "06:00 PM",
    noOfSeatsAvailable: 24,
    layout: {
      rows: 12,
      seatsPerRow: 4,
      seatConfiguration: [
        ["1A", "1B", "1C", "1D"],
        ["2A", "2B", "2C", "2D"],
        ["3A", "3B", "3C", "3D"],
        ["4A", "4B", "4C", "4D"],
        ["5A", "5B", "5C", "5D"],
        ["6A", "6B", "6C", "6D"],
        ["7A", "7B", "7C", "7D"],
        ["8A", "8B", "8C", "8D"],
        ["9A", "9B", "9C", "9D"],
        ["10A", "10B", "10C", "10D"],
        ["11A", "11B", "11C", "11D"],
        ["12A", "12B", "12C", "12D"],
      ],
    },
    seatCategories: [
      { name: "Business", price: 200, rows: [0, 1] }, // Rows 1-2 are Business Class
      { name: "First Class", price: 150, rows: [2, 3, 4] }, // Rows 3-5 are First Class
      { name: "Economy", price: 100, rows: [5, 6, 7, 8, 9, 10, 11] }, // Rows 6-12 are Economy Class
    ],
  },
];


